AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31  # <-- REQUIRED for SAM
Resources:
  EmailManagerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: 3000

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: python-dependencies
      Description: Dependencies for HelloWorldFunction
      ContentUri: layer.zip
      CompatibleRuntimes:
        - python3.12
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 600
      Architectures:
        - x86_64
      Layers:
        - !Ref DependenciesLayer
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: '{{resolve:secretsmanager:dev/email_manager_client_credentials:SecretString:email_manager_client_id}}'
          GOOGLE_CLIENT_SECRET: '{{resolve:secretsmanager:dev/email_manager_client_credentials:SecretString:email_manager_client_secret}}'
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref EmailManagerApi
            Path: /hello_world
            Method: GET
