AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  CallbackURL:
    Type: String
    Description: The callback URL for the Cognito User Pool Client.

  LogoutURL:
    Type: String
    Description: The logout URL for the Cognito User Pool Client.
    
Resources:
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/cognito.yaml
      Parameters:
        CallbackURL: !Ref CallbackURL
        LogoutURL: !Ref LogoutURL
  

  Dependencies:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/dependencies.yaml
  
  DynamoDB:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/dynamo_db.yaml

  Lambdas:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/lambdas.yaml
      Parameters:
        RequestsLayerArn: !GetAtt Dependencies.Outputs.RequestsLayerArn
        GmailLayerArn: !GetAtt Dependencies.Outputs.GmailLayerArn
        VertexAILayerArn: !GetAtt Dependencies.Outputs.VertexAILayerArn
        AuthUserPoolId: !GetAtt Cognito.Outputs.AuthUserPoolId
        AuthUserPoolARN: !GetAtt Cognito.Outputs.AuthUserPoolARN
        AuthUserPoolClientId: !GetAtt Cognito.Outputs.AuthUserPoolClientId
        AuthDomain: !GetAtt Cognito.Outputs.AuthDomain
        CallbackURL: !Ref CallbackURL

