AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CoreLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: requests-dependencies
      ContentUri: ../dependencies/core.zip
      CompatibleRuntimes:
        - python3.12

  GoogleLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: google-dependencies
      Description: Dependencies for Google API
      ContentUri: ../dependencies/google.zip
      CompatibleRuntimes:
        - python3.12

Outputs:
  CoreLayerArn:
    Description: The ARN of the Core dependency layer.
    Value: !Ref CoreLayer

  GoogleLayerArn:
    Description: The ARN of the Google API dependency layer.
    Value: !Ref GoogleLayer
