AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  RequestsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: requests-dependencies
      ContentUri: ../dependencies/requests
      Description: Dependencies for HelloWorldFunction
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12
      BuildRequirements:
        - requests==2.32.4
        - google-api-python-client==2.173.0
        - google-auth==2.40.3
        - google-auth-httplib2==0.2.0
        - httplib2==0.22.0
        - PyJWT==2.10.1
        - cryptography==45.0.5
        - cffi==1.17.1
        - pycparser==2.22
        - six==1.16.0
        - wheel==0.43.0
        - setuptools==70.0.0
        - pip==24.0

  GmailLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: gmail-dependencies
      Description: Dependencies for Gmail API
      ContentUri: ../dependencies/gmail
      CompatibleRuntimes:
        - python3.12

  VertexAILayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: vertex-ai-dependencies
      Description: Dependencies for Vertex AI API
      ContentUri: ../dependencies/vertex_ai
      CompatibleRuntimes:
        - python3.12

  LambdaSRCLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: lambda-src-dependencies
      Description: Dependencies for Lambda source
      ContentUri: ../dependencies/lambda_src
      CompatibleRuntimes:
        - python3.12

Outputs:
  RequestsLayerArn:
    Description: The ARN of the Requests dependency layer.
    Value: !Ref RequestsLayer

  GmailLayerArn:
    Description: The ARN of the Gmail API dependency layer.
    Value: !Ref GmailLayer

  VertexAILayerArn:
    Description: The ARN of the Vertex AI API dependency layer.
    Value: !Ref VertexAILayer
  
  LambdaSRCLayerArn:
    Description: The ARN of the Lambda source dependency layer.
    Value: !Ref LambdaSRCLayer
