AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31 
Resources:
  GoogleOAuthAccessTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserTokens
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: Production

  GmailHistoryIdTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GmailHistoryId
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: Production

  GmailCustomLabelsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CustomLabels
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: title
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      Tags:
        - Key: Environment
          Value: Production

Outputs:
  GoogleOAuthAccessTokensTableArn:
    Value: !GetAtt GoogleOAuthAccessTokensTable.Arn
    Description:  "DynamoDB Table ARN for the user google oauth tokens"
  GoogleOAuthAccessTokensTableName:
    Value: !Ref GoogleOAuthAccessTokensTable
    Description: "DynamoDB Table Name for the user google oauth tokens"
  GmailHistoryIdTableArn:
    Value: !GetAtt GmailHistoryIdTable.Arn
    Description: "DynamoDB Table ARN for the user gmail history ids"
  GmailHistoryIdTableName:
    Value: !Ref GmailHistoryIdTable
    Description: "DynamoDB Table Name for the user gmail history ids"
  GmailCustomLabelsTableArn:
    Value: !GetAtt GmailCustomLabelsTable.Arn
    Description: "DynamoDB Table ARN for the user gmail custom labels"
  GmailCustomLabelsTableName:
    Value: !Ref GmailCustomLabelsTable
    Description: "DynamoDB Table Name for the user gmail custom labels"